data:extend({
	{
		type = "item",
		name = PLORD.pfx .. "charcoal",
		icon = PLORD.asset_icon .. "charcoal.png",
		icon_size = 64, icon_mipmaps = 4,
		burnt_result = "PLORD_charcoal_ash_slag",
		fuel_category = "chemical",
		fuel_value = "2.7MJ",
		subgroup = "raw-resource",
		order = "b[coal]-b",
		stack_size = 50,
		pictures = {
			{filename = PLORD.asset_icon .. "charcoal.png", size = 64, scale = 0.5},
		},
    weight = 1 * kg,
	},
	{
		type = "item",
		name = PLORD.pfx .. "charcoal_ash_slag",
		icon = PLORD.asset_icon .. "carbonium/coal_ash.png",
		icon_size = 64, icon_mipmaps = 4,
		subgroup = "raw-resource",
		order = "g[resin-ore]-e",
		stack_size = 100,
		pictures = {
			{filename = PLORD.asset_icon .. "carbonium/coal_ash.png", size = 64, scale = 0.5},
		},
    weight = 200 * grams,
	},
	{
		type = "item",
		name = PLORD.pfx .. "charcoal_ash",
		icon = PLORD.asset_icon .. "carbonium/coal_ash.png",
		icon_size = 64, icon_mipmaps = 4,
		subgroup = "raw-resource",
		order = "g[resin-ore]-e",
		stack_size = 100,
		pictures = {
			{filename = PLORD.asset_icon .. "carbonium/coal_ash.png", size = 64, scale = 0.5},
		},
    weight = 100 * grams,
	},
	{
		type = "item",
		name = PLORD.pfx .. "charcoal_slag",
		icon = PLORD.asset_icon .. "carbonium/coal_slag.png",
		icon_size = 64, icon_mipmaps = 4,
		subgroup = "raw-resource",
		order = "g[resin-ore]-e",
		stack_size = 100,
		pictures = {
			{filename = PLORD.asset_icon .. "carbonium/coal_slag.png", size = 64, scale = 0.5},
		},
    weight = 100 * grams,
	},
	{
		type = "item",
		name = PLORD.pfx .. "coal_ash_slag",
		icon = PLORD.asset_icon .. "carbonium/coal_ash.png",
		icon_size = 64, icon_mipmaps = 4,
		subgroup = "raw-resource",
		order = "g[resin-ore]-e",
		stack_size = 100,
		pictures = {
			{filename = PLORD.asset_icon .. "carbonium/coal_ash.png", size = 64, scale = 0.5},
		},
    weight = 350 * grams,
	},
	{
		type = "item",
		name = PLORD.pfx .. "coal_ash",
		icon = PLORD.asset_icon .. "carbonium/coal_ash.png",
		icon_size = 64, icon_mipmaps = 4,
		subgroup = "raw-resource",
		order = "g[resin-ore]-e",
		stack_size = 100,
		pictures = {
			{filename = PLORD.asset_icon .. "carbonium/coal_ash.png", size = 64, scale = 0.5},
		},
    weight = 150 * grams,
	},
	{
		type = "item",
		name = PLORD.pfx .. "coal_slag",
		icon = PLORD.asset_icon .. "carbonium/coal_slag.png",
		icon_size = 64, icon_mipmaps = 4,
		subgroup = "raw-resource",
		order = "g[resin-ore]-e",
		stack_size = 100,
		pictures = {
			{filename = PLORD.asset_icon .. "carbonium/coal_slag.png", size = 64, scale = 0.5},
		},
    weight = 150 * grams,
	},
})
