require(PLORD.attr_exts .. "armament/turrets_items")
require(PLORD.attr_exts .. "armament/turrets_recipes")
require(PLORD.attr_exts .. "armament/weapons_items")
require(PLORD.attr_exts .. "armament/weapons_recipes")
require(PLORD.attr_exts .. "armament/equipment_items")
require(PLORD.attr_exts .. "armament/equipment_recipes")